kind: CronJob
metadata:
  annotations: {}
  name: ecr-cred-helper
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: app-job
            image: davit/k8s-app-job
            imagePullPolicy: IfNotPresent
            env:
            - name: MONGO_IP
              value: mongo
            resources: {}
            securityContext:
              capabilities: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30